# Generated by Django 3.1.7 on 2022-11-28 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 28, 23, 53, 43, 498387), verbose_name='发送时间'),
        ),
    ]
